# Боксплот и тест Манна-Уитни

## Боксплот

<dl class="fnkc-required">
  <dt>data</dt>
  <dd>данные</dd>

  <dt>group</dt>
  <dd>группа по оси X</dd>

  <dt>numbers</dt>
  <dd>значения по оси Y</dd>

  <dt>lim</dt>
  <dd>
    <p>минимальное и максимальное значение на оси Y</p>
    <p>можно поставить NA вместо числа и значение определится автоматически</p>
  </dd>

  <dt>breaks</dt>
  <dd>подписи на оси Y</dd>
</dl>

<dl class="fnkc-optional">
  <dt>labs</dt>
  <dd>подписи осей</dd>

  <dt>base_size</dt>
  <dd>размер текста</dd>

  <dt>width</dt>
  <dd>ширина сохраняемого графика</dd>

  <dt>height</dt>
  <dd>высота сохраняемого графика</dd>
</dl>

<div class="sourceCode"><pre><code><span><span class='kw'><a href='https://rdrr.io/r/base/library.html'>library</a></span><span class='op'>(</span><span class='va'><a href='https://tidyverse.tidyverse.org'>tidyverse</a></span><span class='op'>)</span></span>
<span></span>
<span><span class='va'>plot_data</span> <span class='op'>&lt;-</span> <span class="fnkc-required" data-toggle="fnkc-help" data-content="данные"><span class='va'>data</span></span></span>
<span></span>
<span><span class='fu'><a href='https://ggplot2.tidyverse.org/reference/ggplot.html'>ggplot</a></span><span class='op'>(</span><span class='va'>plot_data</span>, <span class='fu'><a href='https://ggplot2.tidyverse.org/reference/aes.html'>aes</a></span><span class='op'>(</span><span class="fnkc-required" data-toggle="fnkc-help" data-content="группа по оси X">x <span class='op'>=</span> <span class='va'>group</span></span>, <span class="fnkc-required" data-toggle="fnkc-help" data-content="значения по оси Y">y <span class='op'>=</span> <span class='va'>numbers</span></span><span class='op'>)</span><span class='op'>)</span> <span class='op'>+</span></span>
<span>  <span class='fu'><a href='https://ggplot2.tidyverse.org/reference/geom_boxplot.html'>geom_boxplot</a></span><span class='op'>(</span><span class='op'>)</span> <span class='op'>+</span></span>
<span>  <span class='fu'><a href='https://ggplot2.tidyverse.org/reference/scale_continuous.html'>scale_y_continuous</a></span><span class='op'>(</span><span class="fnkc-required" data-toggle="fnkc-help" data-content="минимальное и максимальное значение на оси Y">lim <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='op'>-</span><span class='fl'>3</span>, <span class='fl'>3</span><span class='op'>)</span></span>, <span class="fnkc-required" data-toggle="fnkc-help" data-content="подписи на оси Y">breaks <span class='op'>=</span> <span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span><span class='op'>(</span><span class='op'>-</span><span class='fl'>3</span>, <span class='op'>-</span><span class='fl'>2</span>, <span class='op'>-</span><span class='fl'>1</span>, <span class='fl'>0</span>, <span class='fl'>1</span>, <span class='fl'>2</span>, <span class='fl'>3</span><span class='op'>)</span></span><span class='op'>)</span> <span class='op'>+</span></span>
<span>  <span class="fnkc-optional" data-toggle="fnkc-help" data-content="подписи осей"><span class='fu'><a href='https://ggplot2.tidyverse.org/reference/labs.html'>labs</a></span><span class='op'>(</span></span></span>
<span>    <span class="fnkc-optional" data-toggle="fnkc-help" data-content="подпись оси X">x <span class='op'>=</span> <span class='st'>"Подпись оси X"</span>,</span></span>
<span>    <span class="fnkc-optional" data-toggle="fnkc-help" data-content="подпись оси Y">y <span class='op'>=</span> <span class='st'>"Подпись оси Y"</span></span>
<span>  <span class="fnkc-optional" data-toggle="fnkc-help" data-content="подписи осей"><span class='op'>)</span></span></span></span> <span class='op'>+</span>
<span>  <span class='fu'><a href='https://ggplot2.tidyverse.org/reference/ggtheme.html'>theme_classic</a></span><span class='op'>(</span><span class="fnkc-optional" data-toggle="fnkc-help" data-content="размер текста">base_size <span class='op'>=</span> <span class='fl'>13</span></span><span class='op'>)</span></span>
<span></span>
<span></span><span><span class='fu'><a href='https://ggplot2.tidyverse.org/reference/ggsave.html'>ggsave</a></span><span class='op'>(</span><span class='st'>"plot.png"</span>, <span class="fnkc-optional" data-toggle="fnkc-help" data-content="ширина сохраняемого графика">width <span class='op'>=</span> <span class='fl'>4</span></span>, <span class="fnkc-optional" data-toggle="fnkc-help" data-content="высота сохраняемого графика">height <span class='op'>=</span> <span class='fl'>5</span></span><span class='op'>)</span></span>
</code></pre><button type="button" class="btn btn-copy" title="" aria-label="Copy to clipboard" data-toggle="popover" data-placement="top" data-trigger="hover" data-original-title="Copy to clipboard"><i class="bi"></i></button></div>


## Тест Манна-Уитни

<dl>
  <dt>data</dt>
  <dd>данные</dd>

  <dt>numbers</dt>
  <dd>значения</dd>

  <dt>group</dt>
  <dd>группа</dd>
</dl>

<div class="sourceCode"><pre><code><span><span class='fu'><a href='https://rdrr.io/r/stats/wilcox.test.html'>wilcox.test</a></span><span class='op'>(<span class="fnkc-required" data-toggle="fnkc-help" data-content="значения"><span class='va'>numbers</span></span> <span class='op'>~</span> <span class="fnkc-required" data-toggle="fnkc-help" data-content="группа"><span class='va'>group</span></span>, <span class="fnkc-required" data-toggle="fnkc-help" data-content="данные"><span class='va'>data</span></span><span class='op'>)</span></span></code></pre><button type="button" class="btn btn-copy" title="" aria-label="Copy to clipboard" data-toggle="popover" data-placement="top" data-trigger="hover" data-original-title="Copy to clipboard"><i class="bi"></i></button></div>

## Тест Манна-Уитни для всех пар

<dl>
  <dt>data</dt>
  <dd>данные</dd>

  <dt>numbers</dt>
  <dd>значения</dd>

  <dt>group</dt>
  <dd>группа</dd>

  <dt>p.adjust.method</dt>
  <dd>
    поправка
    <ul>
      <li>none - нет</li>
      <li>holm - Бонферрони-Холма</li>
      <li>fdr - False Discovery Rate</li>
    </ul>
  </dd>
</dl>

<div class="sourceCode"><pre><code><span><span class='fu'><a href='https://rdrr.io/r/stats/pairwise.wilcox.test.html'>pairwise.wilcox.test</a></span><span class='op'>(</span><span class="fnkc-required" data-toggle="fnkc-help" data-content="значения"><span class='va'>data</span><span class='op'>$</span><span class='va'>numbers</span></span>, <span class="fnkc-required" data-toggle="fnkc-help" data-content="группа"><span class='va'>data</span><span class='op'>$</span><span class='va'>group</span></span>, <span class="fnkc-required" data-toggle="fnkc-help" data-content="поправка">p.adjust.method <span class='op'>=</span> <span class='st'>"holm"</span></span><span class='op'>)</span></span></code></pre><button type="button" class="btn btn-copy" title="" aria-label="Copy to clipboard" data-toggle="popover" data-placement="top" data-trigger="hover" data-original-title="Copy to clipboard"><i class="bi"></i></button></div>

---

Загрузить скрипт [06-boxplot.R](scripts/06-boxplot.R)

<script>
$(function () {
  $('span[data-toggle="fnkc-help"]').popover({
    trigger: "hover"
  });
})
</script>
