project:
  type: website
  output-dir: docs

website:
  title: "Практика по R в ДГОИ"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Введение"
        href: index.qmd
      - text: "Установка"
        href: 02-install.Rmd
      - text: "Проекты"
        href: 03-create-project.Rmd
      - text: "Базовый R"
        href: 04-practice1.Rmd
      - text: "Чтение данных"
        href: 05-read-data.Rmd
      - text: "Боксплоты"
        href: 06-boxplot.Rmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
